package com.ruinedlexicon.peuler;

public class Main {

    public static void main(String[] args) {
    /*
     *  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     *  By starting with 1 and 2, the first 10 terms will be:
     *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     *  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     *  find the sum of the even-valued terms.
     *  */

    long a = 1;
    long b = 2;
    long c = 0;
    long sum = 2;

    // Count Fibonacci forever until we hit 4 Million
        // Only sum if the number is even

        System.out.println(a);
        System.out.println(b);
        while (c < 4000000) {
            // Calculate the next iteration
            c = a + b;
            if (c < 100){
                System.out.println(c);
            }

            // Shift registers for next calculation
            a = b;
            b = c;

            // Sum if needed
            if (c % 2 == 0) {
                sum += c;
            }
        }

        System.out.printf("Sum of even Fibonacci less than 4 Million is %d", sum);
    }
}
